DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS score;
DROP TABLE IF EXISTS game;
DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS user_game;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE score (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  score INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE game (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  host_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  num_of_questions INTEGER NOT NULL,
  FOREIGN KEY (host_id) REFERENCES user (id)
);

CREATE TABLE question (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  game_id INTEGER NOT NULL,
  num INTEGER NOT NULL,
  a INTEGER NOT NULL,
  b INTEGER NOT NULL,
  answer INTEGER NOT NULL,
  FOREIGN KEY (game_id) REFERENCES game (id)
);

CREATE TABLE user_game (
  user_id INTEGER NOT NULL,
  game_id INTEGER NOT NULL,
  PRIMARY KEY (user_id, game_id),
  FOREIGN KEY (user_id) REFERENCES user (id),
  FOREIGN KEY (game_id) REFERENCES game (id)
);
